-- ===================================================
-- V1: Schema inicial do sistema de oficina mecânica
-- ===================================================

CREATE TABLE IF NOT EXISTS clients (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150)  NOT NULL,
    cpf_cnpj        VARCHAR(14)   NOT NULL UNIQUE,
    client_type     VARCHAR(2)    NOT NULL,
    email           VARCHAR(100),
    phone           VARCHAR(20),
    created_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vehicles (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate    VARCHAR(10)  NOT NULL UNIQUE,
    brand            VARCHAR(50)  NOT NULL,
    model            VARCHAR(80)  NOT NULL,
    production_year  INT          NOT NULL,
    client_id        BIGINT       NOT NULL REFERENCES clients(id),
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS parts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)   NOT NULL,
    description     VARCHAR(255),
    unit_price      DECIMAL(10,2)  NOT NULL,
    stock_quantity  INT            NOT NULL DEFAULT 0,
    unit            VARCHAR(10)    NOT NULL,
    created_at      TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS service_items (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        VARCHAR(100)   NOT NULL,
    description                 VARCHAR(255),
    base_price                  DECIMAL(10,2)  NOT NULL,
    estimated_duration_minutes  INT            NOT NULL,
    active                      BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at                  TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS work_orders (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number          VARCHAR(20)    UNIQUE,
    client_id             BIGINT         NOT NULL REFERENCES clients(id),
    vehicle_id            BIGINT         NOT NULL REFERENCES vehicles(id),
    status                VARCHAR(25)    NOT NULL DEFAULT 'RECEIVED',
    notes                 VARCHAR(500),
    total_cost            DECIMAL(10,2)  NOT NULL DEFAULT 0,
    created_at            TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP      NOT NULL DEFAULT NOW(),
    diagnosis_started_at  TIMESTAMP,
    sent_for_approval_at  TIMESTAMP,
    approved_at           TIMESTAMP,
    execution_started_at  TIMESTAMP,
    finished_at           TIMESTAMP,
    delivered_at          TIMESTAMP,
    cancelled_at          TIMESTAMP
);

CREATE TABLE IF NOT EXISTS work_order_parts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id  BIGINT         NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
    part_id        BIGINT         NOT NULL REFERENCES parts(id),
    quantity       INT            NOT NULL,
    unit_price     DECIMAL(10,2)  NOT NULL
);

CREATE TABLE IF NOT EXISTS work_order_services (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id   BIGINT         NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
    service_item_id BIGINT         NOT NULL REFERENCES service_items(id),
    price           DECIMAL(10,2)  NOT NULL,
    notes           VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS app_users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)   NOT NULL UNIQUE,
    password    VARCHAR(255)  NOT NULL,
    role        VARCHAR(20)   NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_clients_cpf_cnpj    ON clients(cpf_cnpj);
CREATE INDEX IF NOT EXISTS idx_vehicles_plate       ON vehicles(license_plate);
CREATE INDEX IF NOT EXISTS idx_vehicles_client      ON vehicles(client_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_status   ON work_orders(status);
CREATE INDEX IF NOT EXISTS idx_work_orders_client   ON work_orders(client_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_vehicle  ON work_orders(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_wo_parts_order       ON work_order_parts(work_order_id);
CREATE INDEX IF NOT EXISTS idx_wo_services_order    ON work_order_services(work_order_id);
