-- ===================================================
-- V4: Solicitações operacionais (maker-checker)
--     Atendente solicita; somente ADMIN aprova/executa.
--     Cobre ajuste de estoque e cancelamento de OS.
-- ===================================================

CREATE TABLE IF NOT EXISTS operation_requests (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type               VARCHAR(30)   NOT NULL,   -- STOCK_ADJUSTMENT | WORK_ORDER_CANCELLATION
    status             VARCHAR(15)   NOT NULL DEFAULT 'PENDING', -- PENDING | APPROVED | REJECTED
    target_id          BIGINT        NOT NULL,   -- partId ou workOrderId
    target_description VARCHAR(150),             -- snapshot p/ exibição (nome da peça / nº da OS)
    adjustment         INT,                      -- somente para ajuste de estoque
    reason             VARCHAR(255)  NOT NULL,   -- justificativa obrigatória
    requested_by       VARCHAR(100)  NOT NULL,
    requested_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    decided_by         VARCHAR(100),
    decided_at         TIMESTAMP,
    decision_note      VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_operation_requests_status ON operation_requests(status, requested_at);
